/*
  Written by JelleWho

  Pre-made drinks mixes are stored in the Website
*/
//Ingredients can NOT have a "." or "," or "-" in them!
enum IngredientE {UNK, VODKA, GIN, ORANGE_JUICE, RUM, CRANBERRY_JUICE, LEMONADE, TRIPLE_SEC, LEMON_JUICE, COLA, SPRITE, TEQUILA, GRENADINE_SYRUP, MILK, PINEAPPLE_JUICE, LIME_JUICE, PEACH_TREE, WHITE_RUM, TONIC_WATER, WATERMELON_VODKA, GINGER_ALE, SIMPLE_SYRUP, WHISKY, LEMON_SODA};
String IngredientS[] = {"UNK", "VODKA", "GIN", "ORANGE_JUICE", "RUM", "CRANBERRY_JUICE", "LEMONADE", "TRIPLE_SEC", "LEMON_JUICE", "COLA", "SPRITE", "TEQUILA", "GRENADINE_SYRUP", "MILK", "PINEAPPLE_JUICE", "LIME_JUICE", "PEACH_TREE", "WHITE_RUM", "TONIC_WATER", "WATERMELON_VODKA", "GINGER_ALE", "SIMPLE_SYRUP", "WHISKY", "LEMON_SODA"};
